function GetLoadingMessage() as string

    messages = [
        "Now loading...",
        "One moment please...",
        "Downloading the internet...",
        "Unclogging the tubes...",
        "Warming up the flux capacitor...",
        "Loading, ehm, stuff...",
        "Restoring quantum entanglement...",
        "Searching for kitten videos...",
        "One Mississippi... two Mississippi...",
        "Checking the TV's extended warranty...",
        "Deleting system32...",
        "Updating: 3 hours 32 minutes remaining...",
        "Asking ChatGPT for humorous loading messages...",
        "Loading today's sponsor... NordVPN!",
        "Don't worry, this is normal...",
        "Don't forget to like and subscribe...",
        "Shoveling coal into the server...",
        "Counting down from infinity...",
    ]

    index = GetRandom(0, messages.count() - 1)
    return messages[index]
end function

function GetRandom(min as integer, max as integer) as integer
    dateTime = CreateObject("roDateTime")
    random = Rnd(max) + dateTime.GetMilliseconds()
    return min + (random mod (max - min + 1))
end function
